### ISSUE TITLE
ReadOnlySpan<byte> support?

### ISSUE THREAD

**Issue by abrasat** [StephenCleary/HashAlgorithms#4]
@StephenCleary  I am using the library in my applications and it works great. Is it possible to compute the crc32 hash also from a ReadOnlySpan<byte>, additionally to the hash computation from byte[]? If not, could this feature be added?

**Comment by StephenCleary** [comment]
Are you on .NET Core yet? If so, this is already implemented.

The `HashAlgorithm` base type [added support](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.hashcore?view=net-7.0&WT.mc_id=DT-MVP-5000058#system-security-cryptography-hashalgorithm-hashcore(system-readonlyspan((system-byte)))) for `ReadOnlySpan<byte>` in .NET Core 2.1. When used on .NET Core 2.1 or newer platforms, Nito.HashAlgorithms already provides the span-based overloads, avoiding all the `byte[]` array allocations.

**Comment by abrasat** [comment]
Yes, I am on .NET 6, thanks for the hint!
One more question regarding the usage of ComputeHash (Stream). Actually I have a MemoryStream where I get the raw byte-array  with myStream.GetBuffer(), to avoid the byte-array copy. Is there any reason why the ComputeHash (Stream) and  method does not have the option to set the "offset" and "length" parameters, to be able to compute the hash only for the specified region of the byte array inside the stream? I mean similarly with ComputeHash(byte[] buffer, int offset, int count)

**Comment by StephenCleary** [comment]
Bearing in mind that `ComputeHash(Stream)` is a Microsoft API and not one provided by this library, I would guess that the reason is that stream-based APIs just don't normally follow that pattern. I'm not aware of any other BCL API that takes a stream with offset/length parameters.

`ComputeHash(Stream)` is more of a convenience API that reads the bytes out of the stream and then passes them to other `ComputeHash` methods. If you know you have a `MemoryStream` and can call `GetBuffer`, then it would be more efficient to call that and call the lower-level `ComputeHash` methods. `ComputeHash(Stream)` has to deal with general-purpose streams, so it would always read them out into a separate buffer.

**Comment by abrasat** [comment]
ok, thx for the clarification
